[versions]
spring-boot = "3.0.0"
tomcat = "10.1.1"
jacoco = "0.8.8"
spotless = "6.12.0"
mapstruct = "1.5.3.Final"
commonsIo = "2.11.0"
bouncycastle = "1.72"
jsoup = "1.15.3"

bootstrap-core = "5.2.3"
bootstrap-icons = "1.10.2"
datatables = "1.13.1"
jquery = "3.6.1"

gradleGitProperties = "2.4.1"
graalvmNative = "0.9.18"
undercouchDownload = "5.3.0"

[libraries]
bouncycastle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvmNative" }
gitProperties = { id = "com.gorylenko.gradle-git-properties", version.ref = "gradleGitProperties"}
download = { id = "de.undercouch.download", version.ref = "undercouchDownload" }
