spring:
  datasource:
    url: "jdbc:h2:mem:test"
  h2:
    console:
      enabled: true
tsa:
  certificate:
    path: "classpath:dev/mieser/tsa/app/rsa.p12"
  http:
    port: 8079
  server:
    port: 3018
