name: Check

on:
  push:
    branches:
      - develop
      - feature/**
  pull_request:
    branches:
      - develop
      - feature/**

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Gradle 'build' Task
        run: ./gradlew build
